name: Run

on:
  workflow_dispatch:
    inputs:
      method:
        required: true
        default: 'GET'
      target:
        required: true
      time:
        default: '60'
      threads:
        default: '100'
      ratelimit:
        default: '0'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make executable
        run: chmod +x h2

      - name: Run
        run: ./h2 ${{ inputs.method }} ${{ inputs.target }} ${{ inputs.time }} ${{ inputs.threads }} ${{ inputs.ratelimit }} --full --turbo --conns 128
